python: can't open file '../py_scripts/utilscripts/verify_dise_blore.py': [Errno 2] No such file or directory
